spring:
  datasource:
    url: jdbc:mysql://49.235.23.118:3306/demo?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  profiles:
    include:
      - mybatis